### ISSUE TITLE
Script Error: waiting for function failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by ianneub** [flood-io/chrome#3]
Hello, I'm trying to run the tutorial script located here: https://chrome.flood.io/examples/scenario_1_wordpress.html

I am running the test with:
`flood verify test.ts`

On the first step I am getting this error:
```
Test: Start
        visit()
        wait()
        Script Error

Error: waiting for function failed: timeout 30000ms exceeded

        x step failed
```

Here is the code running the first step:
```
step('The Flood Store: Home', async browser => {

        await browser.visit('https://jriz.io')

        let pageTextVerify = By.visibleText("Welcome to the Flood IO Merchandise Store.")
        await browser.wait(Until.elementIsVisible(pageTextVerify))

    })
```

Any help would be appreciated. As I am new to Flood it could very well be some setting or something simple that I missed.

Thanks in advance!

**Comment by ianneub** [comment]
Subsequent tries worked, so not sure why it wasn't working before. Although I can't get the same code to work on my website, I'll keep trying and then open another issue if needed. Sorry for the trouble.

**Comment by ivanvanderbyl** [comment]
@ianneub thanks for reporting. We're working on open sourcing the actual test engine, which will make debugging issues like this one much easier.
